name: Latest blog post - Medium

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
# sets the permission to write to the repository
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@tsjdevapps"
          comment_tag_name: "MEDIUM-BLOG-POST-LIST"
          max_post_count: 10
